source/hello/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from webapp.views.albums import AlbumsView, UpdateAlbum, AlbumView, CreateAlbum, DeleteAlbum
from webapp.views.photos import IndexView, PhotoView, CreatePhoto, UpdatePhoto, DeletePhoto

app_name = "webapp"





urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('photo/add/', CreatePhoto.as_view(), name="create_photo"),
    path('photo/<int:pk>/', PhotoView.as_view(), name="photo_view"),
    path('photo/<int:pk>/update/', UpdatePhoto.as_view(), name="update_photo"),
    path('photo/<int:pk>/delete/', DeletePhoto.as_view(), name="delete_photo"),
    path('albums/', AlbumsView.as_view(), name="album_index"),
    path('album/<int:pk>/update/', UpdateAlbum.as_view(), name="update_album"),
    path('album/<int:pk>/', AlbumView.as_view(), name="album_view"),
    path('album/add/', CreateAlbum.as_view(), name="create_album"),
    path('album/<int:pk>/delete/', DeleteAlbum.as_view(), name="delete_album"),



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Photo(models.Model):
    image = models.ImageField(upload_to="fotos", null=False, blank=False, verbose_name="Фотография")
    signature = models.CharField(max_length=30, null=False, blank=False, verbose_name="Подпись")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    author = models.ForeignKey(get_user_model(), null=False, blank=False, related_name="photos", verbose_name="Автор",
                               on_delete=models.CASCADE)
    album = models.ForeignKey("webapp.Album", null=True, blank=True, on_delete=models.CASCADE, related_name="albums_photo",
                              verbose_name="Альбом")

    def __str__(self):
        return f"{self.id}. {self.image}. {self.signature}. {self.created_at}. {self.album}. {self.author}"

    class Meta:
        db_table = "photos"
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"


class Album(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False, verbose_name="Название")
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name="Описание")
    author_album = models.ForeignKey(get_user_model(), null=False, blank=False, related_name="albums",
                                     verbose_name="Автор альбома",
                                     on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")


    def __str__(self):
        return f"{self.id}. {self.name}. {self.description}. {self.author_album}. {self.created_at}. "

    class Meta:
        db_table = "albums"
        verbose_name = "Альбом"
        verbose_name_plural = "Альбомы"

source/webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Photo, Album


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["image", "signature", "album"]


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ["name", "description"]


class PhotoDeleteForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["image", "signature", "album"]

source/webapp/views/albums.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView


from webapp.forms import AlbumForm
from webapp.models import Album


class AlbumsView(ListView):
    model = Album
    template_name = "albums/albums_index.html"
    context_object_name = "albums"
    ordering = "-created_at"


class AlbumView(DetailView):
    template_name = "albums/album_view.html"
    model = Album


class CreateAlbum(LoginRequiredMixin, CreateView):
    form_class = AlbumForm
    template_name = "albums/album_create.html"

    def form_valid(self, form):
        user = self.request.user
        form.instance.author_album = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:album_view", kwargs={"pk": self.object.pk})


class UpdateAlbum(UpdateView):
    form_class = AlbumForm
    template_name = "albums/album_update.html"
    model = Album

    def get_success_url(self):
        return reverse("webapp:album_view", kwargs={"pk": self.object.pk})


class DeleteAlbum(DeleteView):
    model = Album
    template_name = "albums/album_delete.html"
    success_url = reverse_lazy('webapp:index')

source/webapp/views/photos.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PhotoForm, PhotoDeleteForm
from webapp.models import Photo


class IndexView(ListView):
    model = Photo
    template_name = "photos/index.html"
    context_object_name = "photos"
    ordering = "-created_at"


class PhotoView(DetailView):
    template_name = "photos/photo_view.html"
    model = Photo


class CreatePhoto(LoginRequiredMixin, CreateView):
    form_class = PhotoForm
    template_name = "photos/create.html"

    def form_valid(self, form):
        user = self.request.user
        form.instance.author = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:photo_view", kwargs={"pk": self.object.pk})


class UpdatePhoto(PermissionRequiredMixin,UpdateView):
    form_class = PhotoForm
    template_name = "photos/update.html"
    model = Photo

    def get_success_url(self):
        return reverse("webapp:photo_view", kwargs={"pk": self.object.pk})


class DeletePhoto(DeleteView):
    model = Photo
    template_name = "photos/delete.html"
    success_url = reverse_lazy('webapp:index')

source/webapp/templates/photos/create.html
{% extends "base.html" %}
{% block title %}Добавление фотографии{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Добавление фотографии</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include "partial/form.html" with button_text="Создать" %}
        </form>
        <a href="{% url "webapp:index" %}">На главную</a>
    </div>
{% endblock %}

source/webapp/templates/photos/delete.html
{% extends "base.html" %}
{% block title %}Удаление фотографии{% endblock %}

{% block content %}
    <h2>Удалить фото: {{ photo.signature }}?</h2>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn">Да</button>
    </form>
    <a class="btn" href="{% url "webapp:photo_view" photo.pk %}">Нет</a>
{% endblock %}

source/webapp/templates/photos/index.html
{% extends "base.html" %}
{% block nav %}
    <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:album_index" %}">Альбомы</a>
        </li>
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_photo" %}">Добавление фотографии</a>
        </li>

    {% endif %}
{% endblock %}
{% block content %}
    <div class="row">
    <div class=" row">
            {% include "photos/photo_list_view.html" %}
        </div>
    </div>
{% endblock %}

source/webapp/templates/photos/photo_list_view.html
{% block content %}
{% for photo in photos.all %}
            <div class="card col-12 col-md-6 col-lg-4" style="width: 18rem;">
                <img src="{{ photo.image.url }}" class="card-img-top" alt="#">
                <div class="card-body">
                    <a class="card-title" href="{% url "webapp:photo_view" photo.pk %}">Подпись:{{ photo.signature }}</a>
                    <h5 class="card-title">Автор: {{ photo.author }}</h5>
                    <h5 class="card-title">Дата добавления: {{ photo.created_at }}</h5>
                    <p>Альбом: {{ photo.album.name }}</p>
                </div>
            </div>
        {% endfor %}
{% endblock %}

source/webapp/templates/photos/photo_view.html
{% extends "base.html" %}
{% block nav %}
        {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:create_photo" %}">Добавление фотографии</a>
    </li>
    {% if perms.webapp.change_photo or user == photo.author %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:update_photo" photo.pk %}">Редактировать</a>
        </li>
    {% endif %}
    {% if perms.webapp.delete_photo or user == photo.author %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:delete_photo" photo.pk %}">Удалить</a>
        </li>
    {% endif %}
           <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:delete_photo" photo.pk %}">Альбомы</a>
        </li>


        {% endif %}
{% endblock %}

{% block content %}
    <div class="card col-12 col-md-6 col-lg-4" style="width: 18rem;">
        <img src="{{ photo.image.url }}" class="card-img-top" alt="#">
        <div class="card-body">
            <h5 class="card-title">Подпись: {{ photo.signature }}</h5>
            <h5 class="card-title">Автор: {{ photo.author }}</h5>
            <h5 class="card-title">Дата добавления: {{ photo.created_at }}</h5>
            <a href="{{ photo.album }}" class="card-link btn btn-primary">Альбом</a>
        </div>
    </div>
{% endblock %}

source/webapp/templates/photos/update.html
{% extends "base.html" %}
{% block title %}Редактирование фотографии{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Редактирование фотографии</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include "partial/form.html" with button_text="Изменить" %}
        </form>
        <a href="{% url "webapp:index" %}">На главную</a>
    </div>
{% endblock %}