source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, ChangeProfileView, ChangePasswordView, \
    EmailConfirmView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', ChangeProfileView.as_view(), name="change_profile"),
    path('email-confirm/<str:token>/', EmailConfirmView.as_view(), name="email_confirm"),

]

source/hello/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from datetime import timedelta
from secrets import token_urlsafe

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


# Create your models here.


class Profile(models.Model):
    birthday = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True, verbose_name="Аватар")
    user = models.OneToOneField(get_user_model(),
                                on_delete=models.CASCADE,
                                verbose_name="Пользователь",
                                related_name="profile")


class Token(models.Model):
    TOKEN_LIFETIME_SECONDS = 2 * 60 * 60

    token = models.CharField(max_length=50, unique=True, default=token_urlsafe)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def is_expired(self):
        return self.created_at + timedelta(seconds=self.TOKEN_LIFETIME_SECONDS) < timezone.now()

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    # email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'email']


class UserChangeForm(forms.ModelForm):
    # email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = { 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birthday', 'avatar']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.exceptions import BadRequest
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from accounts.models import Profile, Token

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = MyUserCreationForm

class EmailConfirmView(View):
    def get(self, request, *args, **kwargs):
        token_str = kwargs.get("token")
        token = get_object_or_404(Token, token=token_str)
        if token.is_expired():
            raise BadRequest()
        user = token.user
        user.is_active = True
        user.save()
        login(self.request, user)
        token.delete()
        return redirect("webapp:index")


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "profile.html"
    paginate_by = 6
    paginate_orphans = 0
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        paginator = Paginator(self.get_object().articles.all(),
                              self.paginate_by,
                              self.paginate_orphans)
        page_number = self.request.GET.get('page', 1)
        page_object = paginator.get_page(page_number)
        context = super().get_context_data(**kwargs)
        context['page_obj'] = page_object
        context['articles'] = page_object.object_list
        context['is_paginated'] = page_object.has_other_pages()
        return context


class ChangeProfileView(PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = "change_user.html"
    profile_form_class = ProfileChangeForm
    context_object_name = "user_obj"

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "profile_form" not in context:
            context["profile_form"] = self.profile_form_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        profile_form = self.profile_form_class(instance=self.object.profile,
                                               data=request.POST,
                                               files=request.FILES)
        if form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        # self.get_form()
        form.save()
        profile_form.save()
        return redirect("accounts:profile", self.object.pk)

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))


class ChangePasswordView(PasswordChangeView):
    # model = User
    # form_class = PasswordChangeForm
    template_name = "change_password.html"


    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.request.user.pk})

source/accounts/templates/change_user.html
{% extends "base.html" %}

{% block content %}
    <div class="text-center">
        <h1>Редактирование профиля</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include "partial/form.html" with fields_only=True %}
            {% include "partial/form.html" with form=profile_form button_text="Редактировать"%}
        </form>
    </div>
{% endblock %}

source/accounts/templates/login.html
{% extends "base.html" %}

{% block title %}Вход{% endblock %}
{% block content %}
    <h1>Вход</h1>
    <div class="text-center">
        <form method="post" class="w-50 ms-auto me-auto">
            {% csrf_token %}
            {% if has_error %}
                <p class="text-danger">Неверное имя пользователя или пароль.</p>
            {% endif %}
            <div class="form-group">
                <label for="username" class="form-label">Имя пользователя:</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Пароль:</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <button class="mt-3 btn btn-outline-dark" type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

source/accounts/templates/profile.html
{% extends "base.html" %}

{% block title %}Профиль{% endblock %}
{% block nav %}
    {% if user_obj == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_profile' user_obj.pk %}">Редактировать</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Сменить пароль</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card flex-row mt-3">
        {% if user_obj.profile.avatar %}
            <img src="{{ user_obj.profile.avatar.url }}" class="card-img-top w-25" alt="...">
        {% endif %}
{#        <div class="card-body ms-5">#}
{#            <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>#}
{#            <h6 class="card-subtitle mb-2 text-muted">Год рождения: {{ user_obj.profile.birthday }}</h6>#}
{#            <h6 class="card-subtitle mb-2 text-muted">Имя: {{ user_obj.first_name }}</h6>#}
{#            <h6 class="card-subtitle mb-2 text-muted">Фамилия: {{ user_obj.last_name }}</h6>#}
{#            <h6 class="card-subtitle mb-2 text-muted">Почта: {{ user_obj.email }}</h6>#}
{#        </div>#}
{#    </div>#}
{#    {% include "partial/articles_list_partial.html" %}#}
{% endblock %}

source/accounts/templates/registration.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}
{% block content %}
    <h1>Регистрация</h1>
    <form method="post">
    {% include 'partial/form.html' with button_text='Зарегистрироваться' %}


    </form>

{% endblock %}