source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, ChangeProfileView, ChangePasswordView, \
    EmailConfirmView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/change/', ChangeProfileView.as_view(), name="change_profile"),
    path('email-confirm/<str:token>/', EmailConfirmView.as_view(), name="email_confirm"),

]

source/hello/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from webapp.views.albums import AlbumsView, UpdateAlbum, AlbumView, CreateAlbum, DeleteAlbum
from webapp.views.photos import IndexView, PhotoView, CreatePhoto, UpdatePhoto, DeletePhoto

app_name = "webapp"





urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('photo/add/', CreatePhoto.as_view(), name="create_photo"),
    path('photo/<int:pk>/', PhotoView.as_view(), name="photo_view"),
    path('photo/<int:pk>/update/', UpdatePhoto.as_view(), name="update_photo"),
    path('photo/<int:pk>/delete/', DeletePhoto.as_view(), name="delete_photo"),
    path('albums/', AlbumsView.as_view(), name="album_index"),
    path('album/<int:pk>/update/', UpdateAlbum.as_view(), name="update_album"),
    path('album/<int:pk>/', AlbumView.as_view(), name="album_view"),
    path('album/add/', CreateAlbum.as_view(), name="create_album"),
    path('album/<int:pk>/delete/', DeleteAlbum.as_view(), name="delete_album"),



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Photo(models.Model):
    image = models.ImageField(upload_to="fotos", null=False, blank=False, verbose_name="Фотография")
    signature = models.CharField(max_length=30, null=False, blank=False, verbose_name="Подпись")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    author = models.ForeignKey(get_user_model(), null=False, blank=False, related_name="photos", verbose_name="Автор",
                               on_delete=models.CASCADE)
    album = models.ForeignKey("webapp.Album", null=True, blank=True, on_delete=models.CASCADE, related_name="albums_photo",
                              verbose_name="Альбом")

    def __str__(self):
        return f"{self.id}. {self.image}. {self.signature}. {self.created_at}. {self.album}. {self.author}"

    class Meta:
        db_table = "photos"
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"


class Album(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False, verbose_name="Название")
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name="Описание")
    author_album = models.ForeignKey(get_user_model(), null=False, blank=False, related_name="albums",
                                     verbose_name="Автор альбома",
                                     on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")


    def __str__(self):
        return f"{self.id}. {self.name}. {self.description}. {self.author_album}. {self.created_at}. "

    class Meta:
        db_table = "albums"
        verbose_name = "Альбом"
        verbose_name_plural = "Альбомы"

source/webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Photo, Album


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["image", "signature", "album"]


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ["name", "description"]


class PhotoDeleteForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["image", "signature", "album"]

source/webapp/views/albums.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView


from webapp.forms import AlbumForm
from webapp.models import Album


class AlbumsView(ListView):
    model = Album
    template_name = "albums/albums_index.html"
    context_object_name = "albums"
    ordering = "-created_at"


class AlbumView(DetailView):
    template_name = "albums/album_view.html"
    model = Album


class CreateAlbum(LoginRequiredMixin, CreateView):
    form_class = AlbumForm
    template_name = "albums/album_create.html"

    def form_valid(self, form):
        user = self.request.user
        form.instance.author_album = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:album_view", kwargs={"pk": self.object.pk})


class UpdateAlbum(UpdateView):
    form_class = AlbumForm
    template_name = "albums/album_update.html"
    model = Album

    def get_success_url(self):
        return reverse("webapp:album_view", kwargs={"pk": self.object.pk})


class DeleteAlbum(DeleteView):
    model = Album
    template_name = "albums/album_delete.html"
    success_url = reverse_lazy('webapp:index')

source/webapp/views/photos.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PhotoForm, PhotoDeleteForm
from webapp.models import Photo


class IndexView(ListView):
    model = Photo
    template_name = "photos/index.html"
    context_object_name = "photos"
    ordering = "-created_at"


class PhotoView(DetailView):
    template_name = "photos/photo_view.html"
    model = Photo


class CreatePhoto(LoginRequiredMixin, CreateView):
    form_class = PhotoForm
    template_name = "photos/create.html"

    def form_valid(self, form):
        user = self.request.user
        form.instance.author = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:photo_view", kwargs={"pk": self.object.pk})


class UpdatePhoto(PermissionRequiredMixin,UpdateView):
    form_class = PhotoForm
    template_name = "photos/update.html"
    model = Photo

    def get_success_url(self):
        return reverse("webapp:photo_view", kwargs={"pk": self.object.pk})


class DeletePhoto(DeleteView):
    model = Photo
    template_name = "photos/delete.html"
    success_url = reverse_lazy('webapp:index')

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{% block title %}Главная{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url "webapp:index" %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mt-3">
                {% block nav%}
                {% endblock %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:logout" %}">Выйти</a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">Здравствуйте <a
                                href="{% url "accounts:profile" request.user.pk %}">{{ user.username }}</a></p>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:registration" %}?next={{ request.get_full_path }}">Зарегистрироваться</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<div class="container">
{% block content %}{% endblock %}
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>